name: docs

on:
  push:
    branches:
      - opensource
      - main
  pull_request:

jobs:
  test-notebooks-examples:
    continue-on-error: True
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pip install -e ."[dev]"

      - name: Notebook tests
        run: |
          tox -e py3.12-nb
